### ISSUE TITLE
Issues tryin to delete vdirs or apps

### ISSUE THREAD

**Issue by lmayorga1980** [simondean/puppet-iis#14]
Hi,

I have the following resource using the iis module

``` ruby
  iis_vdir {'Default_Web_Site':
    ensure          => absent,
   }
```

I have the following error:

``` ruby
Error: Parameter name failed on Iis_vdir[Default_Web_Site]: Invalid value "Default_Web_Site". Valid values match /.+\/.*/.
```

**Comment by simondean** [comment]
Hi. Looks like you need at least one forward slash in the vdir (virtual directory) name

Sent from my iPhone

On 16 Aug 2013, at 20:24, "Luis Mayorga" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I have the following resource using the iis module

{code}

iis_vdir {'Default_Web_Site':
ensure => absent,
}
{code}

I have the following error:

{code}
Error: Parameter name failed on Iis_vdir[Default_Web_Site]: Invalid value "Default_Web_Site". Valid values match /.+\/.*/.
{code}

##

**Comment by lmayorga1980** [comment]
I was using hiera with your module and fix it with this approach.

``` ruby
  each($pools) |$value| { iis_apppool { $value[0] : ensure => absent, } }
  each($sites) |$value| { iis_site    { $value[0] : ensure => absent, } }
  each($apps)   |$key, $value| { iis_app  { "$key/" : ensure => absent, applicationpool => "$key/" } }
  each($vdirs)  |$key, $value| { iis_vdir { "$key/" : ensure => absent, iis_app => "$key/", } }
```
