### ISSUE TITLE
Puppet-iis issue

### ISSUE THREAD

**Issue by mamtag** [simondean/puppet-iis#2]
Hi I am working on simondan\iis module but getting issues-

1) I have Lunix CentOS(Master) machine and windows as Agent machine.
2) I have successfully install and build simondean\iis module on linux machine.
3) I have added iis class to window node.

Now when i am doing 'run puppet agent' from window machine getting error every time as below-

Error on run puppetagent cmd-

Running Puppet agent on demand ...
info: Retrieving plugin
err: Could not retrieve catalog from remote server: Error 400 on SERVER: Could n
ot autoload iis_site: Could not autoload /etc/puppetlabs/puppet/modules/iis/lib/
puppet/provider/iis_site/iis_site.rb: no such file to load -- ../iis_object at /
etc/puppetlabs/puppet/modules/iis/manifests/init.pp:4 on node eqxomsdev
warning: Not using cache on failed catalog
err: Could not retrieve catalog; skipping run
Press any key to continue . . .

Please guide how i can come over from this error.One time, along with above error i got finished catalogl also.

**Comment by binford2k** [comment]
Simon, you will need to write code that's usable on ruby 1.8.7 for this to be usable for most windows users.

**Comment by simondean** [comment]
Already on it :-)

**Comment by simondean** [comment]
Hi mamtag.  I have a new version of the module that might help.  Are you downloading the module from Puppet Forge or here on GitHub?

**Comment by binford2k** [comment]
She's using the Forge.

I've tested it and it's working, except that your example code doesn't enable an aspx script handler.

Thanks for the quick response!

**Comment by simondean** [comment]
Thanks for the info.  I'm just fixing an issue with nested virtual directories and I'll do a Forge release.

**Comment by simondean** [comment]
Hi.  I've released a new version 0.1.1 of the module to Puppet Forge.  Let me know if it helps

**Comment by simondean** [comment]
Hi Ben.  With regards to the ASPX script handler, do you know whether it would be resolved by installing some of Window's features like IIS-WebServer and NetFx3 via Puppet Labs' dism module.  Something like: 

dism { 'IIS-WebServer':
  ensure => present,
}

dism { 'NetFx3':
  ensure => present,
}

Not sure whether other features would be needed too.

**Comment by binford2k** [comment]
I actually don't know anything about IIS. I installed a test machine to
verify the issues she was having.

-Ben
Sent from my iPhone

On Aug 11, 2012, at 12:58 AM, Simon Dean notifications@github.com wrote:

Hi Ben. With regards to the ASPX script handler, do you know whether it
would be resolved by installing some of Window's features like
IIS-WebServer and NetFx3 via Puppet Labs' dism module. Something like:

dism { 'IIS-WebServer':
ensure => present,
}

dism { 'NetFx3':
ensure => present,
}

Not sure whether other features would be needed too.

—
Reply to this email directly or view it on
GitHubhttps://github.com/simondean/puppet-iis/issues/2#issuecomment-7664823.

**Comment by mamtag** [comment]
Hi Simon/Ben,

Thanks for help :)

Now I am now able to finish catalog on windows agent successfully as below-

Running Puppet agent on demand ...
info: Retrieving plugin
info: Caching catalog for eqxomsdev
info: Applying configuration version '1344827363'
notice: Finished catalog run in 6.25 seconds
Press any key to continue . . .

But now I am getting issue on My Master machine( Linux +CentOS) while looking from puppet console(Showing fail)-

In Logs seems error as below-

Message    :

1)  err -Could not evaluate: Error 400 on SERVER: Not authorized to call find on /file_metadata/facts Could not retrieve file metadata for puppet://learn.localdomain/facts: Error 400 on SERVER: Not authorized to call find on /file_metadata/facts
2)  err - UTC err Failed to generate additional resources using 'eval_generate: Error 400 on SERVER: Not authorized to call search on /file_metadata/facts with {:ignore=>[".svn", "CVS"], :recurse=>true, :links=>"manage", :checksum_type=>"md5"}
3)  err- Could not find a suitable provider for iis_site
4)  warning - Fact syncing is deprecated as of 0.25 -- use 'pluginsync' instead
5)  notice - Finished catalog run in 3.89 seconds

 Source  :

1)   /File[/var/opt/lib/pe-puppet/facts/]
2)  /File[/var/opt/lib/pe-puppet/facts/]
3)  Puppet
4)  Puppet
5)  puppey

Please guide how i can resolve it?

**Comment by binford2k** [comment]
I do not believe that this is Simon's problem any longer. Relocating back to pe-users.

Can you paste your puppet.conf to gist/pastebin/etc and reply with a link?  Also, paste the output of `tree /etc/puppetlabs/puppet`

Thanks!

On Aug 13, 2012, at 3:28 AM, mamtag notifications@github.com wrote:

> Hi Simon/Ben,
> 
> Thanks for help :)
> 
> Now I am now able to finish catalog on windows agent successfully as below-
> 
> Running Puppet agent on demand ...
> info: Retrieving plugin
> info: Caching catalog for eqxomsdev
> info: Applying configuration version '1344827363'
> notice: Finished catalog run in 6.25 seconds
> Press any key to continue . . .
> 
> But now I am getting issue on My Master machine( Linux +CentOS) while looking from puppet console(Showing fail)-
> 
> In Logs seems error as below-
> 
> Message :
> 
> 1) err -Could not evaluate: Error 400 on SERVER: Not authorized to call find on /file_metadata/facts Could not retrieve file metadata for puppet://learn.localdomain/facts: Error 400 on SERVER: Not authorized to call find on /file_metadata/facts
> 2) err - UTC err Failed to generate additional resources using 'eval_generate: Error 400 on SERVER: Not authorized to call search on /file_metadata/facts with {:ignore=>[".svn", "CVS"], :recurse=>true, :links=>"manage", :checksum_type=>"md5"}
> 3) err- Could not find a suitable provider for iis_site
> 4) warning - Fact syncing is deprecated as of 0.25 -- use 'pluginsync' instead
> 5) notice - Finished catalog run in 3.89 seconds
> 
> Source :
> 
> 1) /File[/var/opt/lib/pe-puppet/facts/]
> 2) /File[/var/opt/lib/pe-puppet/facts/]
> 3) Puppet
> 4) Puppet
> 5) puppey
> 
> Please guide how i can resolve it?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Ben Ford | Professional Services Engineer 
Puppet Labs, Inc.
411 NW Park #500
Portland, OR 97209

509.592.7291
ben.ford@puppetlabs.com

**Comment by mamtag** [comment]
But there is a error like 'err- Could not find a suitable provider for iis_site'.Is it not related to iis module?
Just want to confirm.

**Comment by simondean** [comment]
Sorry for the delay in replying. I agree with Ben, it's probably a more general puppet issue even though it mentions iis_site. Could be something to do with how/where the module is installed on your puppet master. If you resolve the issue, could you close this GitHub issue for me please?

Thanks 
Simon
