### ISSUE TITLE
Quotes around physicalPath in virtual directory cause 'Illegal characters in path'

### ISSUE THREAD

**Issue by vexilar** [simondean/puppet-iis#4]
After deploying an IIS website on a Windows Server 2008 R2 box I went to expand the website in the IIS manager and got the message 'Illegal characters in path' and was unable to expand the website to see its file structure.  I tracked this problem down to get_simple_property_arg in iis_object.  Basically I removed wrapping the argument in quotes, even if it contained spaces.  Seems to be fixing the issue, but I'm worried that I will run into other problems by not wrapping arguments in quotes when they contain spaces to certain appcmd calls.

**Comment by simondean** [comment]
Hi. Could you provide an example of the kind of physical path that's triggering the issue? Could do with seeing whether it just contains spaces or whether it's got things like unix style forward slashes in it. 

Thanks

**Comment by vexilar** [comment]
Here is an example path:  C:\Program Files (x86)\Test Company\Test Website.  Before the fix, when I couldn't expand the website (and thus couldn't browse it), If I right clicked on the website -> manage web site -> advanced settings -> the physical path itself showed quotes around it in the text box like "C:\Program Files (x86)\Test Company\Test Website".  After I made the the fix, the quotes stopped showing up in that text box (and I stopped getting the 'Illegal Characters in Path' trying to expand the website).

**Comment by simondean** [comment]
I've had a good look at this.  The approach you took in removing the quotes was fine.  I've done the same thing myself and all my cucumber-based acceptance tests for the module still pass with that change.  The change you mind is OK as by default Ruby itself wraps in double quotes any argument with a space in it.   

I'll be releasing a new version of the module early this week that will include this change, as well as other things.  

Thanks for raising the issue.

**Comment by vexilar** [comment]
Sweet!  Thanks man.

**Comment by simondean** [comment]
No worries. The release is here: http://forge.puppetlabs.com/simondean/iis/0.1.2

**Comment by vexilar** [comment]
Hey Simon,

I was testing my manifests locally using 'puppet apply' and setting the
modulepath of the agent to somewhere locally on disk (and everything was
working).  However, now that I am serving up the modules from the master, I
cannot get the custom iis types to work.  I have another module, DISM, that
appears to be serving up its custom types with pluginsync just fine.  The
strangest part is that the catalog for the nodes compile fine and when I
look at them I can see that the iis resources are intended to be deployed,
but when i look in /var/lib/puppet/type or provider I do not see the IIS
stuff.  I was wondering if you or anyone else has used this module through
the master and, if so, what I might be doing wrong.

Thanks,
Sean

## 

Sean Wolf
3023 Marion Street
Denver, CO 80205
(720) 340-2749

**Comment by simondean** [comment]
I've had it running with a puppet master and pluginsync and it worked well. It might be worth trying an older release just to make sure it's not a regression.  

Are you using environments btw? Is the module installed in the main modules directory on the master or under an environment specific modules directory?

Cheers
Simon
