### ISSUE TITLE
Puppet-iis issue

### ISSUE THREAD

**Issue by mamtag** [simondean/puppet-iis#5]
Hi Simon,

I am working with IIS module and it worked fine with 5 agent machines and today when i have started on 6th agent machine and i have added manifests for 6th agent and ran puppet agent started getting as below-

I want to tell you that i have installed iis module only one time after that i am copying of that module and changed the init.pp file and module name.

Could ypu please guide me?

Running Puppet agent on demand ...
info: Retrieving plugin
info: Loading facts in C:/Documents and Settings/All Users/Application Data/Pupp
etLabs/puppet/var/lib/facter/facter_dot_d.rb
info: Loading facts in C:/Documents and Settings/All Users/Application Data/Pupp
etLabs/puppet/var/lib/facter/puppet_vardir.rb
info: Loading facts in C:/Documents and Settings/All Users/Application Data/Pupp
etLabs/puppet/var/lib/facter/root_home.rb
info: Caching catalog for webdev01
info: Applying configuration version '1346393748'
err: Could not find a suitable provider for iis_site
err: Could not find a suitable provider for iis_app
err: Could not find a suitable provider for iis_vdir
notice: Finished catalog run in 5.14 seconds
Press any key to continue . . .

**Comment by mamtag** [comment]
Hi Simon,

I have noticed that on 6th agent i have iis6 installed and ths why i am getting issue.
Please guide how i can move forward if i am having IIS6 installed on my agent.

Thanks,
Mamta

**Comment by simondean** [comment]
Hi Mamta.  Unfortunately the module only works with IIS 7 and IIS 7.5.  The module uses the appcmd tool which wasn't available in earlier versions of IIS like IIS 6
