### ISSUE TITLE
ensure => absent

### ISSUE THREAD

**Issue by AlexanderSalmin** [simondean/puppet-iis#7]
Hello,

First I must say what a great module! 
I only have a small issue that I bet you can fix in five minutes..

What  I want;
I want to ensure that we do not have a site called "test", i put the following in my init.pp

iis_site {'test':
        ensure => absent
}

Issue / Bug description;
If site "test" exists, the puppet-client will remove the site and everything is fine. When running next time, and the site does not exists (because we just removed it last run), puppet-client get an error, describing that there is no such site that you want to delete; 

Change from present to absent failed: Execution of 'C:\Windows/system32/inetsrv/appcmd.exe delete site test' returned 1168: ERROR ( message:Cannot find SITE object with identifier "test". )

I guess this can be fixed with some if's and elses provided we have some facter variables to play around with, but since we does not, we cannot rerun the manifest over and over again.

Can you fix this?

Thanks and keep up with the good work!

**Comment by simondean** [comment]
Hi phalcos. Just to check, are you using the latest release of the module? There's an automated test in the module codebase to catch the scenario you describe (the tests are in .feature files in the features directory in the codebase) but there is probably a bug in the test which means it's not caught the issue you've found. Sorry it'll be a few days before I get a chance to look at it and get a fix out.

**Comment by AlexanderSalmin** [comment]
I just wrote that it's working now..

But sorry, my mistake, there is still an issue, i get the same problem with 0.1.2 as with 0.1.1, first deletion works fine, but when puppet-agent has removed the iis site and runs again next time I get the same error.. Back to square one.

**Comment by AlexanderSalmin** [comment]
This is my setup.... If you want to reproduce...

I've put the module/iis from this repository to my /etc/puppetlabs/puppet/modules/ on my enterprise puppet server.

Content of my init.pp
#################

iis_site {'test':
  ensure => absent
}

Running puppet_interactive.bat
##############################

C:\Program Files (x86)\Puppet Labs\Puppet Enterprise\bin>puppet_interactive.bat
Running Puppet agent on demand ...
info: Retrieving plugin
info: Loading facts in C:/ProgramData/PuppetLabs/puppet/var/lib/facter/facter_dot_d.rb
info: Loading facts in C:/ProgramData/PuppetLabs/puppet/var/lib/facter/puppet_vardir.rb
info: Loading facts in C:/ProgramData/PuppetLabs/puppet/var/lib/facter/root_home.rb
info: Caching catalog for pp-puppet-domain.com
info: Applying configuration version '1348153478'

err: Could not prefetch iis_site provider 'iis_site': Execution of 'C:\Windows/system32/inetsrv/appcmd.exe list site /xml /config:*' returned 1: <?xml version="1.0" encoding="UTF-8"?>
<appcmd>
</appcmd>

err: /Stage[main]/Install_app_server/Iis_site[test]/ensure: change from present to absent failed: Execution of 'C:\Windows/system32/inetsrv/appcmd.exe delete site test' returned 1168: ERROR ( message:Cannot find SITE object with identifier "test". )

notice: Finished catalog run in 4.71 seconds
Press any key to continue . . .

**Comment by simondean** [comment]
Hi.  I've had a look at the issue.  Thanks for the info.  From the puppet output you included in your last comment, the error looks to be related to the line: 

err: Could not prefetch iis_site provider 'iis_site': Execution of 'C:\Windows/system32/inetsrv/appcmd.exe list site /xml /config:*' returned 1: <?xml version="1.0" encoding="UTF-8"?>

The second error (the cannot find SITE one) is a symptom of the prefetch failing.  

Do you have any other IIS sites on the machine where you're seeing this issue or is the test site the only site?  I'm wondering whether the following command is failing when no sites are configured in IIS: 

C:\Windows/system32/inetsrv/appcmd.exe list site /xml /config:*

**Comment by simondean** [comment]
Hi phalcos.  I've fixed the issue.  The fix is available here and also as a new release on Puppet Forge (http://forge.puppetlabs.com/users/simondean/modules/iis/releases/0.1.3)
